### ISSUE TITLE
generate requirements.txt again 

### ISSUE THREAD

**Issue by n400peanuts** [neural-data-science-course/single-cell-analysis#3]
requirements.txt at the moment has weird location refs (e.g., anyio @ file:///home/conda/feedstock_root/build_artifacts/anyio_1666191106763/work/dist). This may cause interference for windows users. Try to re-generate requirements. 

You have two options:

1) from [stackoverflow](https://stackoverflow.com/questions/31684375/automatically-create-requirements-txt)
>pip install pipreqs
>pipreqs /path/to/project

2) from [stackoverflow](https://stackoverflow.com/questions/62863020/pip-freeze-generating-file-on-conda-environment)
> pip list --format=freeze > requirements.txt

**Comment by davidespalla** [comment]
Requirements re-generated with option 2
